#' Convert compact membership RDS to long format
#'
#' @param rds_file Path to an RDS file generated by a reproducibility script.
#' @return Long-format data frame.
#' @export
compact_membership_to_long <- function(rds_file) {
  obj <- readRDS(rds_file)
  PP <- as.matrix(obj$membership_matrix)
  unit_names <- obj$unit
  G <- ncol(PP)
  if (is.null(colnames(PP))) colnames(PP) <- paste0("G", seq_len(G))
  data.frame(
    ModelType = obj$metadata$ModelType,
    Scenario = obj$metadata$Scenario,
    Repeat = obj$metadata$Repeat,
    FixedK = obj$metadata$FixedK,
    Unit = rep(unit_names, each = G),
    Cluster = rep(seq_len(G), times = length(unit_names)),
    Latitude = rep(obj$latitude, each = G),
    Longitude = rep(obj$longitude, each = G),
    MembershipProbability = as.numeric(PP),
    stringsAsFactors = FALSE
  )
}

#' Read all compact membership files from a directory
#'
#' @param compact_dir Directory containing compact membership RDS files.
#' @return Combined long-format membership data frame.
#' @export
read_membership_compact <- function(compact_dir) {
  rds_files <- list.files(compact_dir, pattern = "\\.rds$", full.names = TRUE)
  if (length(rds_files) == 0) return(data.frame())
  do.call(rbind, lapply(rds_files, compact_membership_to_long))
}
